### ISSUE TITLE
502 Proxy Error

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/realtimebus-v2#10]
When trying to import data with `import-vdv-and-geometries.sh` script we get this answer from the receiving endpoint:
```
$ tools/import-vdv-and-geometries.sh
Preparing files and assets...
Creating payload...
Importing data...
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.25 (Debian) Server at realtimebusv2.sasabus.org Port 443</address>
</body></html>
All done!
```
Base url is : `https://realtimebusv2.sasabus.org/`

**Comment by danielrampanelli** [comment]
Thanks for the feedback. There seems to be an issue with the automatic download of the required assets, which happens when the command is invoked without parameters. I'll look into it.

Since the actual mapping/paths data by SASA is not (yet) complete and compatible with the import, it is best to use the modified assets which you can download like this

`wget -O latest.zip http://realtimetest.opensasa.info/vdv/list/latest.zip`

`wget -O mapping.csv https://gist.github.com/danielrampanelli/a6cf6f95ec814782e98bce7a0ea49566/raw/7b91def4faeaf847bd388ea686f959330e794d8b/mapping.csv`

`wget -O paths.kml https://gist.github.com/danielrampanelli/a6cf6f95ec814782e98bce7a0ea49566/raw/7b91def4faeaf847bd388ea686f959330e794d8b/paths.kml`

Afterwards, you can invoke the command like this

`tools/import-vdv-and-geometries.sh ./latest.zip ./mapping.csv ./paths.kml`

**Comment by bertolla** [comment]
Ok I will try it like this, but we should remember that this is just a **one-time** solution and that as soon as SASA changes the timetables **this won't work anymore**. Which means the datasets provided by SASA must be valid.
The next change is scheduled in the beginning of June. So we have **only** 3 months to make sure this works properly.

**Comment by danielrampanelli** [comment]
Of course, like we already discussed during the meeting this was only meant to be a temporary solution until the paths are defined correctly by SASA.

**Comment by bertolla** [comment]
Even though it looks way better now and a lot of things work great now the lines are still drawn strangly quiet often. Can we fix this in the datasets?

![Merano](https://user-images.githubusercontent.com/3582457/75681621-3c038400-5c94-11ea-8764-c4d1a51cca6e.png)
![Bolzano](https://user-images.githubusercontent.com/3582457/75681637-43c32880-5c94-11ea-8bcf-109fb51b6aaf.png)
![NOI](https://user-images.githubusercontent.com/3582457/75681645-47ef4600-5c94-11ea-888a-711e22c85fa9.png)

**Comment by danielrampanelli** [comment]
Thanks for the feedback, I'll check the dataset again and I'm gonna make sure all paths are configured correctly.

**Comment by Piiit** [comment]
Archiving
